exports.seed = (knex, Promise) =>
  knex('references').del().then(() =>
    Promise.all([
      knex('references').insert({
        id: 1,
        key: 'angularjs',
        name: 'AngularJS',
        website: 'http://angularjs.org',
        npmjs: 'angular',
        github: 'angular/angular.js',
        stackoverflow: 'angularjs',
      }),
      knex('references').insert({
        id: 2,
        key: 'angular2',
        name: 'Angular 2',
        website: 'https://angular.io',
        npmjs: 'angular2',
        github: 'angular/angular',
        stackoverflow: 'angular2',
      }),
      knex('references').insert({
        id: 3,
        key: 'aurelia',
        name: 'Aurelia',
        website: '',
        npmjs: 'aurelia-cli',
        github: 'aurelia/framework',
        stackoverflow: 'aurelia',
      }),
      knex('references').insert({
        id: 4,
        key: 'backbone',
        name: 'Backbone',
        website: 'http://backbonejs.org',
        npmjs: 'backbone',
        github: 'jashkenas/backbone',
        stackoverflow: 'backbone.js',
      }),
      knex('references').insert({
        id: 5,
        key: 'ember',
        name: 'Ember',
        website: 'http://www.emberjs.com',
        npmjs: 'ember',
        github: 'emberjs/ember.js',
        stackoverflow: 'ember.js',
      }),
      knex('references').insert({
        id: 6,
        key: 'react',
        name: 'React',
        website: 'https://facebook.github.io/react/',
        npmjs: 'react',
        github: 'facebook/react',
        stackoverflow: 'reactjs',
      }),
      knex('references').insert({
        id: 7,
        key: 'vuejs',
        name: 'Vue.js',
        website: 'http://www.emberjs.com',
        npmjs: 'ember-cli',
        github: 'vuejs/vue',
        stackoverflow: 'vue.js',
      }),
    ]));
